# Generated by Django 2.0.1 on 2018-01-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_time', models.DateTimeField(verbose_name='event date')),
                ('event_price', models.FloatField(verbose_name='event price')),
                ('event_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
